### ISSUE TITLE
Problem with gauth

### ISSUE THREAD

**Issue by sata1122** [deathstar/QServ2020#1]
gauth does not seem to be working. I could not find any details regarding this in config files. Is it broken or undocumented? Also, is it disabled by default?

**Comment by deathstar** [comment]
I will have to look into it.

**Comment by deathstar** [comment]
I noticed that local auth works without the server message (grants privs). If you get a chance, try to claim gauth and see if it gives you master without the server message.

**Comment by deathstar** [comment]
@65b9581

**Comment by deathstar** [comment]
local auth has been fixed, working on fixing gauth still.

**Comment by deathstar** [comment]
fixed with https://github.com/deathstar/QServ2020/commit/b76314ab2201f3eeca4b968419e0e438259e5824
