### ISSUE TITLE
new banning system

### ISSUE THREAD

**Issue by ghost** [deathstar/QServ2020#13]
Hello, is there a way you could implment a new banning system so like an example would be assinging a UUID to a spefic user rather then banning the entire ip as banning an entire ip effects other LAN users. I think this would be great as this would fix LAN bans, how this would work is each device/sauerbraten client will have a device_id/UUID and people can ban by username and basically banning them on that device.

**Comment by deathstar** [comment]
Great idea for implementation! I am currently working as a software developer for a legal company full time, and making another game but I haven't forgotten about QServ. I will definetely do some cool stuff soon. I have some code that i wrote about sqlite saved player stats but its buggy. If you want I can make another branch and we can work on that, maybe also talk to people in #sauerservermods https://discord.gg/q9pDKj7X
