### ISSUE TITLE
No makefile

### ISSUE THREAD

**Issue by 2-bithacker** [deathstar/QServ2020#8]
how do I do this on linux without a makefile?  I've always done this stuff with one.  OHHH I got it.  just run `cmake .` in the qserv2020 directory.

**Comment by deathstar** [comment]
Cmake should generate the makefile for you. If the message error still persists after you make your own binary then I can look into it

**Comment by 2-bithacker** [comment]
ik

that's what happened.  thanks!  I was confused, gave up, made the issue, then came back later ad figured it out.
